# Generated by Django 4.1.4 on 2022-12-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=512)),
                ('apellido_paterno', models.CharField(max_length=512)),
                ('apellido_materno', models.CharField(max_length=512)),
                ('ci', models.IntegerField()),
                ('nit', models.IntegerField()),
                ('telefono', models.CharField(max_length=32)),
            ],
        ),
    ]
